colors:

  primary:
    background: '0x1E1E1E'
    foreground: '0xD4D4D4'

  normal:
    black:   '0x808080'
    red:     '0xF44747'
    green:   '0x6A9955'
    yellow:  '0xDCDCAA'
    blue:    '0x569CD6'
    magenta: '0xC586C0'
    cyan:    '0x4EC9B0'
    white:   '0x373737'
