{ config, pkgs, ... }:

{
    home.packages = with pkgs; [
        alacritty
        ani-cli
        brave
        brightnessctl
        cava
        clang
        cmus
        fish
        flameshot
        fzf
        gnumake
        htop
        mpv
        mypy
        neofetch
        nsxiv
        pass
        playerctl
        ripgrep
        rofi
        starship
        streamlink
        sxhkd
        xfce.thunar
        tmux
        trash-cli
        unzip
        xdotool
        xdg-user-dirs
        xterm
        xwallpaper
        yewtube
        yt-dlp
        zip
    ];
}
