import:
  - /home/donny/.config/alacritty/colors/base16-default-dark.yml
  - /home/donny/.config/alacritty/fonts/jetbrains.yml

env:
  TERM: xterm-256color

shell:
  program: fish

window:
  # opacity: 0.9
  opacity: 1
