import:
  - /home/donny/.config/alacritty/colors/base16-gruvbox-dark-hard.yml
  - /home/donny/.config/alacritty/fonts/roboto-mono.yml

env:
  TERM: xterm-256color

shell:
  program: fish

window:
  # opacity: 0.9
  opacity: 1
