#!/bin/sh

bookmark="$(xclip -o)"
file="$HOME/.local/snippets/urls.txt"

if grep -q "^bookmark$" "$file"; then
    notify-send "Already bookmarked!"
else
    notify-send "Bookmark added!"
    echo "$bookmark" >> "$file"
fi
