#!/bin/sh

declare -a machines=("vm" "laptop" "potatopc")

echo "machine:"
read MACHINE_OPTION

IF_FOUND=false

for i in "${machines[@]}"; do
    if [ MACHINE_OPTION == "$i" ]; then
        IF_FOUND=true
    fi
    echo "$i"
done

if [ IF_FOUND != true ]; then
    echo "Machine does not exist!"
    exit 1
else
    rm -rf ~/.config/nvim/lazy-lock.json
    sudo nixos-rebuild switch --flake /etc/nixos#${MACHINE_OPTION}
fi
